# Fine-tuning a model with the Trainer API

Install the Transformers, Datasets, and Evaluate libraries to run this notebook.

In [1]:
from datasets import load_dataset
from transformers import AutoTokenizer, DataCollatorWithPadding

raw_datasets = load_dataset("glue", "mrpc")
checkpoint = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)


def tokenize_function(example):
    return tokenizer(example["sentence1"], example["sentence2"], truncation=True)


tokenized_datasets = raw_datasets.map(tokenize_function, batched=True)
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

In [2]:
from transformers import TrainingArguments

training_args = TrainingArguments("test-trainer", report_to="none")

In [3]:
training_args

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=False,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.NO,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=False,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=test-trainer/runs/Apr09_10-08-22_hwting,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs=None,
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=None,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=3.0,
optim=OptimizerNames.ADAMW_TORCH_FUSED,
optim_args=None,
optim_target_modules=None,
output_dir=test-trainer,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=8,
per_device_train_batch_size=8,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.STEPS,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.0,
warmup_steps=0,
weight_decay=0.0,
)

In [4]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=2)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [5]:
from transformers import Trainer

trainer = Trainer(
    model,
    training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    data_collator=data_collator,
    processing_class=tokenizer,
)

In [6]:
trainer.train()

TrainOutput(global_step=1377, training_loss=0.4931370022509872, metrics={'train_runtime': 233.477, 'train_samples_per_second': 47.131, 'train_steps_per_second': 5.898, 'total_flos': 405114969714960.0, 'train_loss': 0.4931370022509872, 'epoch': 3.0})

In [7]:
predictions = trainer.predict(tokenized_datasets["validation"])
print(predictions.predictions.shape, predictions.label_ids.shape)

(408, 2) (408,)

In [8]:
predictions

PredictionOutput(predictions=array([[-2.165433  ,  1.9793233 ],
       [ 1.2999779 , -1.5742744 ],
       [-0.9824898 ,  0.96254706],
       [-2.1084445 ,  1.9856002 ],
       [ 1.1322777 , -1.4578364 ],
       [-2.1224866 ,  1.9939903 ],
       [-1.9005079 ,  1.7645252 ],
       [-2.1537976 ,  1.9910744 ],
       [-1.8920257 ,  1.7530615 ],
       [-2.083114  ,  1.9623249 ],
       [-2.1640408 ,  1.9802742 ],
       [ 1.1260649 , -1.4434227 ],
       [ 1.14272   , -1.3796258 ],
       [-1.9588805 ,  1.8270752 ],
       [-2.1757307 ,  1.9662751 ],
       [-2.0462637 ,  1.9209642 ],
       [-2.1685104 ,  1.9758868 ],
       [ 1.1288218 , -1.3888916 ],
       [-2.1751235 ,  1.9673883 ],
       [ 1.2150233 , -1.5332977 ],
       [ 1.2307773 , -1.5396758 ],
       [-1.4843098 ,  1.3367866 ],
       [ 0.65602034, -0.82414997],
       [-2.1448143 ,  1.995533  ],
       [-2.165376  ,  1.9783663 ],
       [-0.99590445,  1.0233678 ],
       [-1.6497687 ,  1.4690009 ],
       [-2.175397  ,  1.967122  ],
       [-1.9146504 ,  1.776853  ],
       [-2.143102  ,  1.9955995 ],
       [ 1.0840824 , -1.4174768 ],
       [-2.1768045 ,  1.9653285 ],
       [-2.1631043 ,  1.9830793 ],
       [-1.9855742 ,  1.8559711 ],
       [-2.1365142 ,  1.9977007 ],
       [-2.1351604 ,  1.996499  ],
       [ 0.8168198 , -1.1242802 ],
       [ 1.2794842 , -1.5815108 ],
       [-2.0512514 ,  1.9276999 ],
       [-2.1737564 ,  1.969094  ],
       [ 1.2062718 , -1.5286492 ],
       [-2.1226563 ,  1.9940934 ],
       [-0.20520471,  0.11416454],
       [ 0.8539416 , -1.0591754 ],
       [ 1.0248091 , -1.3103352 ],
       [-2.1502964 ,  1.993366  ],
       [-2.1509893 ,  1.991848  ],
       [ 1.1705902 , -1.4952023 ],
       [-2.1441693 ,  1.996225  ],
       [-2.138377  ,  1.9972955 ],
       [-2.0170434 ,  1.8917826 ],
       [-2.0988233 ,  1.9788748 ],
       [-2.1380744 ,  1.9978237 ],
       [-2.1117864 ,  1.9885232 ],
       [-1.7259854 ,  1.5394258 ],
       [-2.1364133 ,  1.9972218 ],
       [ 0.9941176 , -1.3195782 ],
       [-2.1588867 ,  1.986099  ],
       [-2.1494908 ,  1.9930929 ],
       [-2.007795  ,  1.8779404 ],
       [-0.69783723,  0.70897967],
       [ 0.9619969 , -1.310604  ],
       [-2.1365354 ,  1.9972253 ],
       [-2.1447697 ,  1.9945757 ],
       [-2.0859559 ,  1.9675108 ],
       [ 1.015034  , -1.2989129 ],
       [-2.1714585 ,  1.971731  ],
       [-2.172566  ,  1.9704729 ],
       [ 0.88017523, -1.1945729 ],
       [-2.136798  ,  1.9976382 ],
       [-2.1733744 ,  1.9693024 ],
       [-1.3001826 ,  1.1648926 ],
       [-2.1730099 ,  1.9702392 ],
       [-1.9262115 ,  1.7933136 ],
       [-2.0308025 ,  1.9070132 ],
       [-1.9085631 ,  1.7716717 ],
       [-2.039142  ,  1.915622  ],
       [-2.1670983 ,  1.9764324 ],
       [-2.1360013 ,  1.9975027 ],
       [-2.062391  ,  1.9436936 ],
       [-1.6375593 ,  1.4583648 ],
       [-1.6723702 ,  1.4986244 ],
       [-2.1590095 ,  1.9857967 ],
       [ 0.92319804, -1.2649926 ],
       [-2.1643949 ,  1.9791021 ],
       [ 0.9115668 , -1.2655234 ],
       [-1.8329898 ,  1.6677052 ],
       [-1.5286676 ,  1.3734344 ],
       [-2.1521592 ,  1.9917749 ],
       [-2.1776    ,  1.964127  ],
       [-0.43022028,  0.46531928],
       [-2.1480224 ,  1.9947534 ],
       [-1.966125  ,  1.8324474 ],
       [-2.1639242 ,  1.9802067 ],
       [-2.1474555 ,  1.9948994 ],
       [-2.1485326 ,  1.9931496 ],
       [ 1.1250424 , -1.4262668 ],
       [-1.9345317 ,  1.8014793 ],
       [-1.931104  ,  1.7965893 ],
       [-2.0969377 ,  1.9791098 ],
       [-2.1699095 ,  1.975041  ],
       [-0.48709458,  0.49989843],
       [-2.042287  ,  1.9185673 ],
       [-2.1440258 ,  1.9960537 ],
       [ 0.6368975 , -0.94965583],
       [-2.0837715 ,  1.9649308 ],
       [-1.5533905 ,  1.3871866 ],
       [ 0.92122996, -1.2091519 ],
       [ 1.3034867 , -1.5785996 ],
       [-2.1467874 ,  1.9950608 ],
       [-0.9891226 ,  0.9546081 ],
       [-2.1392145 ,  1.9961821 ],
       [-2.1458688 ,  1.9963793 ],
       [-2.1796963 ,  1.9624443 ],
       [ 0.5963859 , -0.8274689 ],
       [ 0.88695765, -1.2299017 ],
       [-2.0992067 ,  1.9809085 ],
       [-1.9813741 ,  1.8459817 ],
       [-2.168737  ,  1.9740324 ],
       [-2.1745694 ,  1.9674757 ],
       [-2.0529492 ,  1.928901  ],
       [-0.23843437,  0.33129314],
       [ 1.0926408 , -1.4119285 ],
       [-1.8570069 ,  1.7030833 ],
       [-2.1614141 ,  1.9829669 ],
       [-2.16756   ,  1.9767917 ],
       [-2.0692909 ,  1.9493409 ],
       [ 1.2762035 , -1.5922544 ],
       [-2.1764147 ,  1.9647117 ],
       [-2.1441348 ,  1.9959313 ],
       [-2.1147974 ,  1.9892752 ],
       [-2.165934  ,  1.9778197 ],
       [-1.8725003 ,  1.7279297 ],
       [-1.0307826 ,  1.10578   ],
       [-1.8243896 ,  1.6495937 ],
       [-1.7963316 ,  1.6145636 ],
       [-0.5206455 ,  0.5095891 ],
       [ 1.1067134 , -1.397285  ],
       [-2.1682782 ,  1.9751457 ],
       [-2.133029  ,  1.9961342 ],
       [-2.1749246 ,  1.9676594 ],
       [-0.04789403, -0.08012169],
       [ 1.238724  , -1.5471773 ],
       [-2.0269833 ,  1.8980309 ],
       [ 1.3143097 , -1.5886577 ],
       [-1.7272989 ,  1.5331304 ],
       [-2.1764445 ,  1.9667839 ],
       [-0.4255541 ,  0.38766426],
       [-1.7283454 ,  1.532236  ],
       [-2.1141536 ,  1.988699  ],
       [ 1.2567235 , -1.5474977 ],
       [-2.1177924 ,  1.9927771 ],
       [-1.2441982 ,  1.164799  ],
       [-2.1682935 ,  1.9771612 ],
       [-1.4280676 ,  1.3056374 ],
       [-2.1502223 ,  1.9926094 ],
       [-2.1053896 ,  1.983603  ],
       [-1.8218956 ,  1.6417581 ],
       [ 0.7390427 , -1.1177301 ],
       [-1.8054466 ,  1.6231977 ],
       [-1.9472028 ,  1.8173468 ],
       [-2.1331244 ,  1.9972836 ],
       [-2.1775186 ,  1.9643302 ],
       [-2.1492698 ,  1.9928473 ],
       [-2.0881467 ,  1.9687109 ],
       [-2.0760293 ,  1.9592167 ],
       [-1.8844818 ,  1.7415866 ],
       [ 1.1766224 , -1.4770885 ],
       [-2.1446633 ,  1.9953178 ],
       [ 1.1446599 , -1.4634064 ],
       [-1.701634  ,  1.5109383 ],
       [-1.8029745 ,  1.6193033 ],
       [-1.6804509 ,  1.4939713 ],
       [-1.5465873 ,  1.3877947 ],
       [-1.956603  ,  1.8229221 ],
       [-2.1146007 ,  1.9906745 ],
       [-2.1011133 ,  1.981003  ],
       [ 1.2488493 , -1.5409623 ],
       [-2.1619856 ,  1.9812193 ],
       [-2.1679914 ,  1.9749992 ],
       [-0.8800716 ,  0.8581822 ],
       [-0.6897747 ,  0.69189656],
       [-2.1401427 ,  1.9960668 ],
       [-2.161095  ,  1.9829575 ],
       [-1.899034  ,  1.7624266 ],
       [-2.136362  ,  1.995929  ],
       [ 1.2672641 , -1.5501649 ],
       [-2.132769  ,  1.9964334 ],
       [ 1.3160489 , -1.5862572 ],
       [-2.0762594 ,  1.9579263 ],
       [-2.1685    ,  1.9754976 ],
       [ 0.5919931 , -0.9414631 ],
       [-0.05090543, -0.15255764],
       [-2.1612172 ,  1.9828639 ],
       [-1.6384338 ,  1.4572086 ],
       [-1.67283   ,  1.4870135 ],
       [-2.1559484 ,  1.9871279 ],
       [ 1.2517968 , -1.5411886 ],
       [-1.9636521 ,  1.8287331 ],
       [-2.1118205 ,  1.9882427 ],
       [-2.1057327 ,  1.984737  ],
       [-2.1748648 ,  1.9664394 ],
       [ 1.0361917 , -1.3450415 ],
       [-1.8750166 ,  1.7297852 ],
       [-2.0163436 ,  1.8903258 ],
       [ 1.2352718 , -1.538221  ],
       [-2.1094954 ,  1.9872159 ],
       [-1.6199514 ,  1.4409304 ],
       [ 1.1100802 , -1.3911471 ],
       [-1.2643663 ,  1.1692343 ],
       [-0.99385524,  0.9945199 ],
       [-2.080741  ,  1.9597775 ],
       [ 0.881288  , -1.0817938 ],
       [ 0.37891516, -0.59300244],
       [-2.1075191 ,  1.9851683 ],
       [-2.1670468 ,  1.976552  ],
       [-1.6976206 ,  1.5128562 ],
       [-2.1139724 ,  1.9890949 ],
       [ 1.2200513 , -1.5297854 ],
       [-1.5208225 ,  1.3709556 ],
       [-1.997036  ,  1.8629526 ],
       [-2.0464807 ,  1.9176353 ],
       [-2.1685977 ,  1.9754989 ],
       [ 1.2268194 , -1.5467921 ],
       [-2.1483562 ,  1.9939579 ],
       [-2.1307898 ,  1.9968612 ],
       [-2.1665053 ,  1.9779074 ],
       [-1.8469497 ,  1.6868131 ],
       [-2.0955977 ,  1.9756249 ],
       [-2.0875537 ,  1.9694334 ],
       [-2.1405969 ,  1.9965849 ],
       [-2.0930674 ,  1.9750675 ],
       [ 1.0511522 , -1.4136657 ],
       [-1.8224019 ,  1.653778  ],
       [-0.09645794,  0.05390485],
       [-1.4558128 ,  1.3263844 ],
       [-1.8379979 ,  1.6737591 ],
       [ 0.80060446, -1.0619668 ],
       [-1.6880779 ,  1.5011744 ],
       [-0.45402855,  0.48801118],
       [-1.8902007 ,  1.7526534 ],
       [ 1.2826315 , -1.5728714 ],
       [-1.8411692 ,  1.6835898 ],
       [-1.17538   ,  1.1905484 ],
       [-1.9722661 ,  1.8373284 ],
       [-2.1382556 ,  1.9971315 ],
       [-1.9304558 ,  1.7985516 ],
       [-2.049874  ,  1.9274228 ],
       [-2.1668458 ,  1.9768639 ],
       [-1.9773481 ,  1.8463088 ],
       [-1.7129056 ,  1.5210354 ],
       [ 0.66663724, -1.127771  ],
       [-1.1982204 ,  1.1146942 ],
       [-0.36644387,  0.39076042],
       [-1.0515014 ,  1.0365362 ],
       [ 1.3274878 , -1.5946515 ],
       [-2.1496089 ,  1.9928656 ],
       [-1.5452117 ,  1.3878496 ],
       [-2.1629972 ,  1.9813366 ],
       [ 0.31344706, -0.50278383],
       [-2.1041038 ,  1.9820176 ],
       [-2.039655  ,  1.91623   ],
       [-2.1074724 ,  1.9835862 ],
       [-2.1028605 ,  1.9830772 ],
       [-1.6828256 ,  1.4930236 ],
       [ 0.64819413, -0.9229893 ],
       [-2.0515306 ,  1.9303085 ],
       [ 1.2223147 , -1.5251759 ],
       [ 0.14163408, -0.26097602],
       [-1.9807403 ,  1.8512615 ],
       [ 0.88519645, -1.2466288 ],
       [-2.148284  ,  1.9935206 ],
       [-2.1424303 ,  1.9960709 ],
       [-2.159676  ,  1.9845418 ],
       [-2.176541  ,  1.9656284 ],
       [-2.0847924 ,  1.9641209 ],
       [-1.8334445 ,  1.6688935 ],
       [ 0.8913059 , -1.1027898 ],
       [-2.0650287 ,  1.9460527 ],
       [-1.9582236 ,  1.8229728 ],
       [-1.7521755 ,  1.5570717 ],
       [ 0.9072882 , -1.217609  ],
       [-0.95466006,  0.9864027 ],
       [ 1.1685834 , -1.492309  ],
       [ 0.33534485, -0.5903685 ],
       [-2.1263208 ,  1.9949867 ],
       [-2.1649866 ,  1.9809295 ],
       [ 0.01914448, -0.05109291],
       [-2.1439652 ,  1.995638  ],
       [ 1.2080611 , -1.5227329 ],
       [-1.0789219 ,  1.1561209 ],
       [ 1.1454928 , -1.4657394 ],
       [-2.1457393 ,  1.9955871 ],
       [-1.7727114 ,  1.5816737 ],
       [-2.1245294 ,  1.9948378 ],
       [ 1.178865  , -1.5047129 ],
       [ 1.0676701 , -1.3948848 ],
       [-1.990577  ,  1.8632858 ],
       [-2.1725955 ,  1.9702239 ],
       [-1.4150454 ,  1.2886488 ],
       [-2.150319  ,  1.9927201 ],
       [-2.1399965 ,  1.9960775 ],
       [-2.0639768 ,  1.9450524 ],
       [ 1.208619  , -1.5214363 ],
       [-2.056724  ,  1.9353153 ],
       [-2.018615  ,  1.8883555 ],
       [ 1.1704489 , -1.4957371 ],
       [-2.171857  ,  1.9708484 ],
       [ 1.2486025 , -1.5711849 ],
       [-1.504428  ,  1.3604462 ],
       [ 0.5747925 , -1.039864  ],
       [-2.165399  ,  1.9788548 ],
       [-0.7172733 ,  0.7358986 ],
       [ 1.2810737 , -1.5820099 ],
       [-2.097879  ,  1.9773884 ],
       [ 0.87767357, -1.2444597 ],
       [-1.2074947 ,  1.1286843 ],
       [-2.1438527 ,  1.9958903 ],
       [ 0.8472858 , -1.0773913 ],
       [ 1.2203507 , -1.5435053 ],
       [ 0.31075802, -0.6858319 ],
       [ 1.2582968 , -1.5579257 ],
       [ 1.1346804 , -1.3535312 ],
       [-1.8367317 ,  1.6734438 ],
       [ 0.24140492, -0.36351413],
       [-2.174542  ,  1.9687736 ],
       [-1.8119205 ,  1.6392386 ],
       [-2.1454    ,  1.9949592 ],
       [-1.917593  ,  1.7832495 ],
       [-2.1395676 ,  1.9959749 ],
       [-2.1694932 ,  1.9750738 ],
       [-2.1544178 ,  1.9897616 ],
       [-2.1658442 ,  1.9776554 ],
       [-1.695437  ,  1.5015522 ],
       [-2.1622608 ,  1.9826497 ],
       [-1.847835  ,  1.6914155 ],
       [-2.1519115 ,  1.9914544 ],
       [-2.1261296 ,  1.9947293 ],
       [-2.1425245 ,  1.9966322 ],
       [-2.0518923 ,  1.9285989 ],
       [-2.1405916 ,  1.9970323 ],
       [-2.1691651 ,  1.9739761 ],
       [ 1.2257894 , -1.5287365 ],
       [ 0.5679702 , -0.8547176 ],
       [-2.0473065 ,  1.9230511 ],
       [-2.1689682 ,  1.9743854 ],
       [-2.1637628 ,  1.9800664 ],
       [-2.1678443 ,  1.9778358 ],
       [-1.5450133 ,  1.3872159 ],
       [-2.1593564 ,  1.9855376 ],
       [ 0.37274992, -0.48926437],
       [-2.1618676 ,  1.9832541 ],
       [-1.3675355 ,  1.2497091 ],
       [-2.1690764 ,  1.9775356 ],
       [-1.9216219 ,  1.7840723 ],
       [ 1.0948474 , -1.3813169 ],
       [-2.037279  ,  1.9158163 ],
       [-1.5202675 ,  1.3701283 ],
       [-1.9200209 ,  1.7862017 ],
       [-2.0250144 ,  1.9007919 ],
       [ 1.2878431 , -1.5809792 ],
       [-2.134348  ,  1.997472  ],
       [-2.1657228 ,  1.977597  ],
       [ 0.04997298, -0.12703538],
       [-2.1123648 ,  1.9878776 ],
       [-2.175478  ,  1.967747  ],
       [-2.1735816 ,  1.9682078 ],
       [ 0.78340375, -1.1617777 ],
       [-1.6070739 ,  1.4350976 ],
       [-0.4274482 ,  0.40976027],
       [-1.0241225 ,  1.030996  ],
       [-2.1530306 ,  1.9906503 ],
       [-1.8383644 ,  1.6785612 ],
       [-0.9745179 ,  0.94807386],
       [ 1.0119582 , -1.3119987 ],
       [-0.8786943 ,  0.8906811 ],
       [-1.8353429 ,  1.6759074 ],
       [-0.30011266,  0.26098302],
       [-1.9893392 ,  1.857167  ],
       [-2.1404188 ,  1.9975443 ],
       [-1.8536857 ,  1.699036  ],
       [-2.1683223 ,  1.976272  ],
       [-1.7508512 ,  1.5581839 ],
       [-2.1624672 ,  1.9819508 ],
       [-2.0933564 ,  1.9749635 ],
       [-1.7931415 ,  1.6097085 ],
       [-1.9746937 ,  1.846599  ],
       [ 0.49122858, -0.6888305 ],
       [-2.1354206 ,  1.9943115 ],
       [-1.6973139 ,  1.5122826 ],
       [-2.1563735 ,  1.9885517 ],
       [-0.9702438 ,  0.91321135],
       [-2.0607362 ,  1.9401368 ],
       [-2.1647933 ,  1.9796287 ],
       [-1.9329046 ,  1.7999297 ],
       [-2.051385  ,  1.9294399 ],
       [-2.1642923 ,  1.9804013 ],
       [-1.3487011 ,  1.2299843 ],
       [-2.0637474 ,  1.9429103 ],
       [-2.1587076 ,  1.987322  ],
       [ 1.1742846 , -1.4262364 ],
       [-2.1724737 ,  1.9704262 ],
       [-1.1463217 ,  1.2053409 ],
       [ 1.2815517 , -1.551755  ],
       [ 0.62406486, -0.68045026],
       [-2.1722782 ,  1.9699551 ],
       [ 1.0885191 , -1.3698276 ],
       [-2.0775878 ,  1.9585936 ]], dtype=float32), label_ids=array([1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1]), metrics={'test_loss': 0.49065932631492615, 'test_runtime': 3.0153, 'test_samples_per_second': 135.311, 'test_steps_per_second': 16.914})

In [9]:
import numpy as np

preds = np.argmax(predictions.predictions, axis=-1)

In [10]:
import evaluate

metric = evaluate.load("glue", "mrpc")
metric.compute(predictions=preds, references=predictions.label_ids)

{'accuracy': 0.8406862745098039, 'f1': 0.8903878583473862}

In [11]:
def compute_metrics(eval_preds):
    metric = evaluate.load("glue", "mrpc")
    logits, labels = eval_preds
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

In [12]:
training_args = TrainingArguments("test-trainer", report_to="none")
model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=2)

trainer = Trainer(
    model,
    training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    data_collator=data_collator,
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [13]:
trainer.train()

TrainOutput(global_step=1377, training_loss=0.45390338108170786, metrics={'train_runtime': 272.3305, 'train_samples_per_second': 40.407, 'train_steps_per_second': 5.056, 'total_flos': 405114969714960.0, 'train_loss': 0.45390338108170786, 'epoch': 3.0})